CREATE DATABASE IF NOT EXISTS sanosysalvos;
CREATE DATABASE IF NOT EXISTS user;
CREATE DATABASE IF NOT EXISTS reporte;



GRANT ALL PRIVILEGES ON sanosysalvos.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON user.* TO 'root'@'%';
FLUSH PRIVILEGES;

