spring.application.name=Fullstack_lll
spring.datasource.url=jdbc:mysql://localhost:3306/db_sanosysalvos
spring.datasource.username=user_test
spring.datasource.password=password_test

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect