spring.application.name=apiGateway
server.port=8090

# Ruta para Mascotas
spring.cloud.gateway.routes[0].id=mascotas-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/mascotas/**

