spring.application.name=apiGateway
server.port=8090

spring.cloud.gateway.routes[0].id=mascotas-service
spring.cloud.gateway.routes[0].uri=${MASCOTAS_URL:http://localhost:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/mascotas/**

spring.cloud.gateway.routes[1].id=reporte-service
spring.cloud.gateway.routes[1].uri=${REPORTES_URL:http://localhost:8083}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/reportes/**

spring.cloud.gateway.routes[2].id=usuarios-service
spring.cloud.gateway.routes[2].uri=${USUARIOS_URL:http://localhost:8082}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/usuarios/**