spring.application.name=Fullstack_lll
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/sanosysalvos}
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081

# Limitar el pool de Hikari para bases de datos gratuitas
spring.datasource.hikari.maximum-pool-size=1