server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        # --- PRODUCCIÓN ---
        proxy_pass https://api-gateway-jyfs.onrender.com/; 

        # --- LOCAL ---
        # proxy_pass http://api-gateway:8090/;

        # ESTA LÍNEA CORRIGE EL ERROR DE HANDSHAKE SSL:
        proxy_ssl_server_name on;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    } 
}