server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
    # --- PRODUCCIÓN (Descomenta esto para Render) ---
    proxy_pass https://api-gateway-jyfs.onrender.com;

    # --- LOCAL (Mantén esto comentado para subirlo a la nube) ---
    # proxy_pass http://api-gateway:8090;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
}